import assert from "node:assert/strict";
import test from "node:test";

import { importGamePackageAsDraft } from "../app/lib/game-package-import";
import { GAME_PACKAGE_SCHEMA_VERSION } from "../app/lib/game-package";
import { deleteCommerceFixture, prisma, uniqueTestLabel } from "./helpers/test-data";

function createImportPackage(slug: string) {
  return {
    schemaVersion: GAME_PACKAGE_SCHEMA_VERSION,
    source: {
      kind: "AI_ASSISTED",
      toolName: "Import Test Tool",
      toolVersion: "0.1.0",
      notes: "Generated by an automated test."
    },
    game: {
      slug,
      title: "Imported Package Test",
      tagline: "A draft-only import test.",
      description: "Used only by the Game Package importer tests.",
      minPlayers: 4,
      maxPlayers: 8,
      durationMin: 120,
      durationMax: 180,
      themes: ["lake mystery", "locked evidence"],
      contentWarnings: ["dramatic violence"]
    },
    characters: [
      {
        key: "detective-vale",
        name: "Detective Vale",
        publicBio: "A careful investigator.",
        privateBio: "Privately carries the access generator.",
        isRequired: true,
        sortOrder: 1
      },
      {
        key: "archivist",
        name: "The Archivist",
        publicBio: "Keeper of old records.",
        isRequired: false,
        sortOrder: 2
      }
    ],
    rounds: [
      {
        key: "round-1",
        title: "Round 1",
        summary: "Arrival.",
        sortOrder: 1,
        cards: [
          {
            key: "vale-arrival",
            title: "Vale Arrival",
            body: "Find the sealed envelope.",
            visibility: "PLAYER_PRIVATE",
            characterKey: "detective-vale",
            sortOrder: 1
          }
        ]
      }
    ],
    evidence: [
      {
        key: "sealed-envelope",
        title: "Sealed Envelope",
        body: "A coded note waits inside.",
        evidenceType: "DOCUMENT",
        visibility: "PLAYER_PRIVATE",
        roundKey: "round-1",
        characterKey: "detective-vale",
        requiredUnlockRuleKey: "open-sealed-envelope",
        sortOrder: 1
      }
    ],
    mediaAssets: [
      {
        key: "envelope-image",
        title: "Envelope Image",
        description: "Placeholder image.",
        assetType: "IMAGE",
        url: "/media/placeholders/envelope.png",
        mimeType: "image/png",
        visibility: "PLAYER_PRIVATE",
        roundKey: "round-1",
        characterKey: "detective-vale",
        evidenceKey: "sealed-envelope",
        sortOrder: 1
      }
    ],
    digitalArtifacts: [
      {
        key: "restricted-folder",
        title: "Restricted Folder",
        artifactType: "DOCUMENT",
        visibility: "PLAYER_PRIVATE",
        characterKey: "detective-vale",
        evidenceKey: "sealed-envelope",
        requiredUnlockRuleKey: "open-sealed-envelope",
        content: {
          body: "A folder unlocked by a generated code."
        },
        sortOrder: 1
      }
    ],
    characterTools: [
      {
        key: "vale-code-generator",
        title: "Vale Code Generator",
        toolType: "ACCESS_CODE_GENERATOR",
        visibility: "PLAYER_PRIVATE",
        characterKey: "detective-vale",
        config: {
          codeLength: 6
        },
        sortOrder: 1
      }
    ],
    unlockRules: [
      {
        key: "open-sealed-envelope",
        title: "Open Sealed Envelope",
        ruleType: "ACCESS_CODE",
        triggerType: "CODE_ENTRY",
        targetType: "GameEvidence",
        targetKey: "sealed-envelope",
        unlockScope: "PLAYER",
        codeMode: "PARTY_TOOL_CODE",
        requiredRoundKey: "round-1",
        requiredCharacterKey: "detective-vale",
        sourceToolKey: "vale-code-generator",
        status: "DRAFT",
        sortOrder: 1
      }
    ],
    finalReveal: {
      title: "Final Reveal",
      victimCharacterKey: "archivist",
      killerCharacterKey: "detective-vale",
      victimRevealText: "The archivist is the victim.",
      killerRevealText: "Detective Vale has the answer.",
      solutionText: "The sealed envelope revealed the truth.",
      epilogueText: "The test concludes."
    }
  };
}

test("importGamePackageAsDraft creates a draft game version with linked content", async () => {
  const label = uniqueTestLabel("import");
  const slug = `test-package-import-${label}`;
  const emailDomain = `@${slug}.example`;
  await deleteCommerceFixture("test-package-import-", emailDomain);

  try {
    const result = await importGamePackageAsDraft(createImportPackage(slug));

    assert.ok(result.ok);
    assert.equal(result.slug, slug);
    assert.equal(result.summary.characters, 2);
    assert.equal(result.summary.unlockRules, 1);

    const game = await prisma.game.findUniqueOrThrow({
      where: { slug },
      include: {
        versions: {
          include: {
            characters: true,
            rounds: { include: { cards: true } },
            evidence: true,
            mediaAssets: true,
            digitalArtifacts: true,
            characterTools: true,
            unlockRules: true,
            finalReveal: true
          }
        }
      }
    });
    const version = game.versions[0];
    assert.equal(game.status, "DRAFT");
    assert.equal(version.status, "DRAFT");
    assert.deepEqual(version.themes, ["lake mystery", "locked evidence"]);
    assert.deepEqual(version.contentWarnings, ["dramatic violence"]);
    assert.equal(version.sourceKind, "AI_ASSISTED");
    assert.equal(version.sourceToolName, "Import Test Tool");
    assert.equal(version.sourceToolVersion, "0.1.0");
    assert.equal(version.sourceNotes, "Generated by an automated test.");
    assert.equal(version.characters.length, 2);
    assert.equal(version.rounds.length, 1);
    assert.equal(version.rounds[0].cards.length, 1);
    assert.equal(version.evidence.length, 1);
    assert.equal(version.mediaAssets.length, 1);
    assert.equal(version.digitalArtifacts.length, 1);
    assert.equal(version.characterTools.length, 1);
    assert.equal(version.unlockRules.length, 1);
    assert.ok(version.finalReveal);

    const evidence = version.evidence[0];
    const artifact = version.digitalArtifacts[0];
    const unlockRule = version.unlockRules[0];
    const tool = version.characterTools[0];
    assert.equal(unlockRule.targetType, "GameEvidence");
    assert.equal(unlockRule.targetId, evidence.id);
    assert.equal(unlockRule.sourceToolId, tool.id);
    assert.equal(evidence.requiredUnlockRuleId, unlockRule.id);
    assert.equal(artifact.requiredUnlockRuleId, unlockRule.id);
    assert.equal(version.finalReveal.killerCharacterId, version.characters.find((character) => character.key === "detective-vale")?.id);
    assert.equal(version.finalReveal.victimCharacterId, version.characters.find((character) => character.key === "archivist")?.id);
  } finally {
    await deleteCommerceFixture("test-package-import-", emailDomain);
  }
});

test("importGamePackageAsDraft rejects invalid packages and duplicate slugs", async () => {
  const label = uniqueTestLabel("import-duplicate");
  const slug = `test-package-import-${label}`;
  const emailDomain = `@${slug}.example`;
  await deleteCommerceFixture("test-package-import-", emailDomain);

  try {
    const invalidResult = await importGamePackageAsDraft({
      schemaVersion: "wrong",
      game: {
        slug,
        title: "",
        tagline: "",
        description: "",
        minPlayers: 8,
        maxPlayers: 4,
        durationMin: 180,
        durationMax: 120
      },
      characters: [],
      rounds: []
    });
    assert.ok(!invalidResult.ok);
    assert.equal(invalidResult.reason, "invalid-package");
    assert.ok(invalidResult.errors.length > 0);

    const firstImport = await importGamePackageAsDraft(createImportPackage(slug));
    assert.ok(firstImport.ok);
    const duplicateResult = await importGamePackageAsDraft(createImportPackage(slug));
    assert.ok(!duplicateResult.ok);
    assert.equal(duplicateResult.reason, "slug-exists");
    assert.equal(duplicateResult.errors[0].code, "DUPLICATE_GAME_SLUG");
  } finally {
    await deleteCommerceFixture("test-package-import-", emailDomain);
  }
});
